name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  diff:
    name: Get changes
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      changed-app-dir: ${{steps.changed-dir-names.outputs.app_any_changed}}
      changed-client-dir: ${{ steps.changed-dir-names.outputs.client_any_changed }}
      changed-other-dir: ${{ steps.changed-dir-names.outputs.other_any_changed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get list of updated dirs
        id: changed-dir-names
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            app:
              - 'app/**'
            client:
              - 'client/**'
            other:
              - '!client/**'
              - '!app/**'

  changed-client-dir:
    name: 'Run on change client dir'
    timeout-minutes: 1
    needs: diff
    if: needs.diff.outputs.changed-client-dir == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Puts output
        run: |
          echo "Output on change client dir"

  changed-other-dir:
    name: 'Run on change other dir'
    timeout-minutes: 1
    needs: diff
    if: needs.diff.outputs.changed-other-dir == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Puts output
        run: |
          echo "Output on change other dir"

  changed-app-dir:
    name: 'Run on change app dir'
    timeout-minutes: 1
    needs: diff
    if: needs.diff.outputs.changed-app-dir == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Puts output
        run: |
          echo "Output on change app dir"
